import AppToaster from "@/components/providers/AppToaster";
import StoreProvider from "@/components/providers/StoreProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          {children}
          <AppToaster />
        </StoreProvider>
      </body>
    </html>
  );
}
